# This is a basic workflow to help you get started with Actions


 name: Publish package to GitHub Packages
 
 on:
  push:
    branches: [ main ]
  release:
    types: [created]
 jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Step 1 - Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
